version: '3'
services:
  influxdb:
    image: influxdb:1.8
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=meteorology
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  weather-monitor:
    image: ghcr.io/fhnw-ivy/fhnw-ds-cde1-wettermonitor:main
    restart: always
    ports:
      - '6540:6540'
    environment:
      - ENVIRONMENT=production
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
    depends_on:
      - influxdb
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    command: --cleanup --interval 30 --rolling-restart
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  influxdb-storage:
