version: '3'
services:
  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=meteorology
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  weather-monitor:
    build: .
    restart: unless-stopped
    ports:
      - '6540:6540'
    environment:
      - ENVIRONMENT=development
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
