version: '3'
services:
  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  chronograf:
    image: chronograf:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:9000:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

  weather-monitor:
    build: ./src
    restart: unless-stopped
    ports:
      - '6540:6540'
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
  chronograf-storage: